const WHITE  := "<BASEFONT COLOR=#FFFFFF>";
const RED    := "<BASEFONT COLOR=#FF4C4C>";
const YELLOW    := "<BASEFONT COLOR=#FFD300>";
const BLUE   := "<BASEFONT COLOR=#4169E1>";
const ORANGE := "<BASEFONT COLOR=#FFA500>";
const LIGHTGRAY := "<BASEFONT COLOR=#D3D3D3>";
const PURPLE := "<BASEFONT COLOR=#9583AB>";
const GREEN := "<BASEFONT COLOR=#33CC66>";

function GetMagentaMap(value)
	case (value)
		0: return 933;
		1: return 833;
		2: return 733;
		3: return 633;
		4: return 533;
		5: return 433;
		6: return 333;
		7: return 233;
		8: return 133;
		9: return 33;
	endcase
endfunction

